# ci.yml file for GitHub Actions
name: Publish Typedoc to Github Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  build_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Retrieve the cached "node_modules" directory (if present)
        uses: actions/cache@v2
        id: node-cache
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies (if the cached directory was not found)
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: pnpm i

      - name: Test to see if the project compiles
        run: pnpm build

      - name: Perform automated checks
        run: pnpm lint

      - name: Create the docs directory locally in CI
        run: cd apps/app && pnpm doc

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: apps/app/docs
